language: csharp
mono: none
dist: xenial
dotnet: 2.2.203

services:
  - docker

install:
  - dotnet restore ./Rustavi2WebApi/rustavi2WebApi.csproj

script:
  - dotnet build ./Rustavi2WebApi/rustavi2WebApi.csproj

deploy:
  provider: script
  script: bash ./scripts/deploy-heroku-docker.sh $HEROKU_USER_NAME $HEROKU_APP $HEROKU_API_KEY
  on:
    branch: release